### ISSUE TITLE
Home page: Content is less visible to the user & font size differs across content 

### ISSUE THREAD

**Issue by saam-rgb** [seata/seata.github.io#875]
On the Home page of SEATA the Content of "**what is SEATA?**" is _less visible_ to the users. 

![image](https://github.com/user-attachments/assets/7c98e8bb-7c42-4e94-b109-7211440cbcde)

and content font size differs in each part of the home page, and also font typography should be changed for the content. 

### Task

- [ ] Change the typography of the content to **sans-serif**
- [ ] Content font size should match throughout the home page **18px - 20px** will be appropriate
- [ ] Text colour of the content of **What is SEATA?** should be made darker

**Comment by BaseMax** [comment]
+1

**Comment by slievrly** [comment]
@saam-rgb @BaseMax I fully agree with the above suggestion. Are you willing to fix this issue?

**Comment by slievrly** [comment]
@BaseMax After merging this fix PR, the font style displayed on the current official website is not very good, can you continue to optimize it?

**Comment by BaseMax** [comment]
Yes I can, can you provide more details? in phone or desktop or? You wants to decrease font size a bit?

**Comment by slievrly** [comment]
> Yes I can, can you provide more details? in phone or desktop or? You wants to decrease font size a bit?

I think the size and color of this part of the modified font do not match the overall style. Do you have any good suggestions for this?

**Comment by BaseMax** [comment]
https://github.com/apache/incubator-seata-website/pull/888 Please check

**Comment by BaseMax** [comment]
@slievrly any new feedback or comment?

**Comment by navjotmaan** [comment]
Hi, I've noticed this issue and would like to help fix the font visibility in the feature list. I'll be working on a fix for this!
